# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Use build argument and pass it as an environment variable
ARG SA_PASSWORD
ENV SA_PASSWORD=${SA_PASSWORD}

# Required for SQL Server
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express

# Copy the SQL initialization script into the container
COPY init-db.sql /init-db.sql

# Start SQL Server, wait for it to be ready, then execute the initialization script.
CMD /bin/bash -c "\
    /opt/mssql/bin/sqlservr & \
    pid=\$!; \
    echo 'Waiting for SQL Server to start...' && \
    sleep 20 && \
    echo 'Executing initialization script...' && \
    /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -i /init-db.sql && \
    wait \$pid"
